name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!

on: [push]

jobs:
  hola-mundo:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Variable definition
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Run script
        run: python main.py
